MitchGuth/silverTwilightClub

index.html, main.html
Hello @nat-sharpe can you please code review this and then you can create the login from the index.html file.
=> created main page and seperated out login page

.gitignore, schema.sql
=> database schema

schema.sql, seedata.sql
Updated the database schema again, and the seed data for it.
=> Database schema udpates and seed data

login.js, package-lock.json, package.json, server.js
Basic API server initialized with server.js
=> server.js creates and validates tokens

main.css, main.html
Hello @nat-sharpe @somelinuxguy can you please code review these front end changes. Also the main page should be set for input from database(Tables) for our MVP.
=> styling changes for mobile first optimization

main.js, package-lock.json
=> Some basic updates first.

index.html, main.js, server.js
changed index.html to remove the references to 'coffee' that Mitch left in there. (It's ok I'm borrowing code too)
Tried to disable cors. I think I got it. Maybe not.
The form now submits to the JS and processes properly. I see the submission hit the API server, so that's good. I just can't process the response properly. I'll need help with that in the morning, probably from Jonathan because I can't figure out why my response is CORS nonsense and not my data. I probably goofed up the CORS headers. Imma n00b
=> Login stuff

main.js, server.js
Token is now returning properly.
=> omfg the token is coming back.

main.js, server.js
Just a couple lines to store the JWT token in localStorage, with the key  "silvertwilight"
=> store the token locally in the key silvertwilight

index.html, main.css, main.js
Makes dynamic landing, login, create account and enter pages.
=> Create account and login

main.js, schema.sql, seedata.sql, server.js
The create user function runs, and does all the things.
=> Nat and Nathan are amazing, and godlike.

index.html, main.js, server.js
After making account, User is sent to login page. 
Did some syntax tweaks on server.js and removed token-sending part of createUser function.
Tweaked index.html to stop and alert user of empty form fields. Also added another password field and an alert for mis-matched passwords.
=> User sent to login page after creating account. Window alerts catch form errors.

index.html, main.js
=> enter button pulls up game page

main.js, server.js
=> Fetches companies from database and populates DOM

server.js
https://trello.com/c/f0EOhpHY/29-back-end-endpoints-playeraction
Please reference that ticket.
=> action saving endpoint added, tested, working

main.js
=> Fetches strategies and populates list in DOM

main.js
@nat-sharpe Please code review this change as Venues are now visible.
=> Get venues

index.html, main.css, main.js
Added a div with an h2 displaying a message and hiding the money and power action fields so that a player not in the club can't make moves. @nat-sharpe @somelinuxguy please code review for merging.
=> Ui game page update

carlsanford.js, schema.sql, server.js
Just checking in my pseudocode
=> carl pseudo code

index.html, main.js, seedata.sql
Stops user from submitting if bid too low, if bid higher than available money or if any fields blank.
=> Captures action data and sends in correctly-formatted JSON. Also handles edge cases.

index.html, main.js
Fixed a few bugs.
Users cannot see action options if they have no money or power. Goodbye message displayed.
User can submit action option to database.
@somelinuxguy @MitchGuth
=> Fixed bugs with checking stats and submitting actions

index.html, main.js
News is now a list of items. If no news message displays no news(aka for new users).
=> News is now in list form

index.html, main.js
=> fix index merge problems.

index.html, main.css
=> Fixed responsive CSS and added favicon

seedata.sql, server.js
silvertwilight.club:5000/scorecard/
=> scorecard endpoint
